//! \file microplane_correspondence.h

//@HEADER
// ************************************************************************
//
//                             Peridigm
//                 Copyright (2011) Sandia Corporation
//
// Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
// the U.S. Government retains certain rights in this software.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// 1. Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the Corporation nor the names of the
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY SANDIA CORPORATION "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SANDIA CORPORATION OR THE
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Questions?
// David J. Littlewood   djlittl@sandia.gov
// John A. Mitchell      jamitch@sandia.gov
// Michael L. Parks      mlparks@sandia.gov
// Stewart A. Silling    sasilli@sandia.gov
//
// ************************************************************************
//@HEADER
#ifndef MICROPLANE_CORRESPONDENCE_H
#define MICROPLANE_CORRESPONDENCE_H

namespace CORRESPONDENCE {

void initializeMicroplaneM7Model
(
    const double E, 
    const double nu, 
    const double k1, 
    const double k2, 
    const double k3, 
    const double k4 
);

template<typename ScalarT>
void updateMicroplaneM7Stress
(
    const ScalarT* strainRate, 
    const ScalarT* strain, 
    const ScalarT* stressN, 
    const ScalarT* state1N,
    const ScalarT* state2N,
    const ScalarT* state3N,
    const ScalarT* state4N,
    const ScalarT* state5N,
    const ScalarT* state6N,
    const ScalarT* state7N,
    const ScalarT* state8N,
    const ScalarT* state9N,
    const ScalarT* state10N,
    const ScalarT* state11N,
    const ScalarT* state12N,
    const ScalarT* state13N,
    const ScalarT* state14N,
    const ScalarT* state15N,
    const ScalarT* state16N,
    const ScalarT* state17N,
    const ScalarT* state18N,
    const ScalarT* state19N,
    const ScalarT* state20N,
    const ScalarT* state21N,
    const ScalarT* state22N,
    const ScalarT* state23N,
    const ScalarT* state24N,
    const ScalarT* state25N,
    const ScalarT* state26N,
    const ScalarT* state27N,
    const ScalarT* state28N,
    const ScalarT* state29N,
    const ScalarT* state30N,
    const ScalarT* state31N,
    const ScalarT* state32N,
    const ScalarT* state33N,
    const ScalarT* state34N,
    const ScalarT* state35N,
    const ScalarT* state36N,
    const ScalarT* state37N,
    const ScalarT* state38N,
    const ScalarT* state39N,
    const ScalarT* state40N,
    const ScalarT* state41N,
    const ScalarT* state42N,
    const ScalarT* state43N,
    const ScalarT* state44N,
    const ScalarT* state45N,
    const ScalarT* state46N,
    const ScalarT* state47N,
    const ScalarT* state48N,
    const ScalarT* state49N,
    const ScalarT* state50N,
    const ScalarT* state51N,
    const ScalarT* state52N,
    const ScalarT* state53N,
    const ScalarT* state54N,
    const ScalarT* state55N,
    const ScalarT* state56N,
    const ScalarT* state57N,
    const ScalarT* state58N,
    const ScalarT* state59N,
    const ScalarT* state60N,
    const ScalarT* state61N,
    const ScalarT* state62N,
    const ScalarT* state63N,
    const ScalarT* state64N,
    const ScalarT* state65N,
    const ScalarT* state66N,
    const ScalarT* state67N,
    const ScalarT* state68N,
    const ScalarT* state69N,
    const ScalarT* state70N,
    const ScalarT* state71N,
    const ScalarT* state72N,
    const ScalarT* state73N,
    const ScalarT* state74N,
    const ScalarT* state75N,
    const ScalarT* state76N,
    const ScalarT* state77N,
    const ScalarT* state78N,
    const ScalarT* state79N,
    const ScalarT* state80N,
    const ScalarT* state81N,
    const ScalarT* state82N,
    const ScalarT* state83N,
    const ScalarT* state84N,
    const ScalarT* state85N,
    const ScalarT* state86N,
    const ScalarT* state87N,
    const ScalarT* state88N,
    const ScalarT* state89N,
    const ScalarT* state90N,
    const ScalarT* state91N,
    const ScalarT* state92N,
    const ScalarT* state93N,
    const ScalarT* state94N,
    const ScalarT* state95N,
    const ScalarT* state96N,
    const ScalarT* state97N,
    const ScalarT* state98N,
    const ScalarT* state99N,
    const ScalarT* state100N,
    const ScalarT* state101N,
    const ScalarT* state102N,
    const ScalarT* state103N,
    const ScalarT* state104N,
    const ScalarT* state105N,
    const ScalarT* state106N,
    const ScalarT* state107N,
    const ScalarT* state108N,
    const ScalarT* state109N,
    const ScalarT* state110N,
    const ScalarT* state111N,
    const ScalarT* state112N,
    const ScalarT* state113N,
    const ScalarT* state114N,
    const ScalarT* state115N,
    const ScalarT* state116N,
    const ScalarT* state117N,
    const ScalarT* state118N,
    const ScalarT* state119N,
    const ScalarT* state120N,
    const ScalarT* state121N,
    const ScalarT* state122N,
    const ScalarT* state123N,
    const ScalarT* state124N,
    const ScalarT* state125N,
    const ScalarT* state126N,
    const ScalarT* state127N,
    const ScalarT* state128N,
    const ScalarT* state129N,
    const ScalarT* state130N,
    const ScalarT* state131N,
    const ScalarT* state132N,
    const ScalarT* state133N,
    const ScalarT* state134N,
    const ScalarT* state135N,
    const ScalarT* state136N,
    const ScalarT* state137N,
    const ScalarT* state138N,
    const ScalarT* state139N,
    const ScalarT* state140N,
    const ScalarT* state141N,
    const ScalarT* state142N,
    const ScalarT* state143N,
    const ScalarT* state144N,
    const ScalarT* state145N,
    const ScalarT* state146N,
    const ScalarT* state147N,
    const ScalarT* state148N,
    const ScalarT* state149N,
    const ScalarT* state150N,
    const ScalarT* state151N,
    const ScalarT* state152N,
    const ScalarT* state153N,
    const ScalarT* state154N,
    const ScalarT* state155N,
    const ScalarT* state156N,
    const ScalarT* state157N,
    const ScalarT* state158N,
    const ScalarT* state159N,
    const ScalarT* state160N,
    const ScalarT* state161N,
    const ScalarT* state162N,
    const ScalarT* state163N,
    const ScalarT* state164N,
    const ScalarT* state165N,
    const ScalarT* state166N,
    const ScalarT* state167N,
    const ScalarT* state168N,
    const ScalarT* state169N,
    const ScalarT* state170N,
    const ScalarT* state171N,
    const ScalarT* state172N,
    const ScalarT* state173N,
    const ScalarT* state174N,
    const ScalarT* state175N,
    const ScalarT* state176N,
    const ScalarT* state177N,
    const ScalarT* state178N,
    const ScalarT* state179N,
    const ScalarT* state180N,
    const ScalarT* state181N,
    const ScalarT* state182N,
    const ScalarT* state183N,
    const ScalarT* state184N,
    const ScalarT* state185N,
    const ScalarT* state186N,
    const ScalarT* state187N,
    const ScalarT* state188N,
    const ScalarT* state189N,
    const ScalarT* internalEnergyN,
    const ScalarT* inelasticEnergyN,
    ScalarT* stressNP1, 
    ScalarT* state1NP1,
    ScalarT* state2NP1,
    ScalarT* state3NP1,
    ScalarT* state4NP1,
    ScalarT* state5NP1,
    ScalarT* state6NP1,
    ScalarT* state7NP1,
    ScalarT* state8NP1,
    ScalarT* state9NP1,
    ScalarT* state10NP1,
    ScalarT* state11NP1,
    ScalarT* state12NP1,
    ScalarT* state13NP1,
    ScalarT* state14NP1,
    ScalarT* state15NP1,
    ScalarT* state16NP1,
    ScalarT* state17NP1,
    ScalarT* state18NP1,
    ScalarT* state19NP1,
    ScalarT* state20NP1,
    ScalarT* state21NP1,
    ScalarT* state22NP1,
    ScalarT* state23NP1,
    ScalarT* state24NP1,
    ScalarT* state25NP1,
    ScalarT* state26NP1,
    ScalarT* state27NP1,
    ScalarT* state28NP1,
    ScalarT* state29NP1,
    ScalarT* state30NP1,
    ScalarT* state31NP1,
    ScalarT* state32NP1,
    ScalarT* state33NP1,
    ScalarT* state34NP1,
    ScalarT* state35NP1,
    ScalarT* state36NP1,
    ScalarT* state37NP1,
    ScalarT* state38NP1,
    ScalarT* state39NP1,
    ScalarT* state40NP1,
    ScalarT* state41NP1,
    ScalarT* state42NP1,
    ScalarT* state43NP1,
    ScalarT* state44NP1,
    ScalarT* state45NP1,
    ScalarT* state46NP1,
    ScalarT* state47NP1,
    ScalarT* state48NP1,
    ScalarT* state49NP1,
    ScalarT* state50NP1,
    ScalarT* state51NP1,
    ScalarT* state52NP1,
    ScalarT* state53NP1,
    ScalarT* state54NP1,
    ScalarT* state55NP1,
    ScalarT* state56NP1,
    ScalarT* state57NP1,
    ScalarT* state58NP1,
    ScalarT* state59NP1,
    ScalarT* state60NP1,
    ScalarT* state61NP1,
    ScalarT* state62NP1,
    ScalarT* state63NP1,
    ScalarT* state64NP1,
    ScalarT* state65NP1,
    ScalarT* state66NP1,
    ScalarT* state67NP1,
    ScalarT* state68NP1,
    ScalarT* state69NP1,
    ScalarT* state70NP1,
    ScalarT* state71NP1,
    ScalarT* state72NP1,
    ScalarT* state73NP1,
    ScalarT* state74NP1,
    ScalarT* state75NP1,
    ScalarT* state76NP1,
    ScalarT* state77NP1,
    ScalarT* state78NP1,
    ScalarT* state79NP1,
    ScalarT* state80NP1,
    ScalarT* state81NP1,
    ScalarT* state82NP1,
    ScalarT* state83NP1,
    ScalarT* state84NP1,
    ScalarT* state85NP1,
    ScalarT* state86NP1,
    ScalarT* state87NP1,
    ScalarT* state88NP1,
    ScalarT* state89NP1,
    ScalarT* state90NP1,
    ScalarT* state91NP1,
    ScalarT* state92NP1,
    ScalarT* state93NP1,
    ScalarT* state94NP1,
    ScalarT* state95NP1,
    ScalarT* state96NP1,
    ScalarT* state97NP1,
    ScalarT* state98NP1,
    ScalarT* state99NP1,
    ScalarT* state100NP1,
    ScalarT* state101NP1,
    ScalarT* state102NP1,
    ScalarT* state103NP1,
    ScalarT* state104NP1,
    ScalarT* state105NP1,
    ScalarT* state106NP1,
    ScalarT* state107NP1,
    ScalarT* state108NP1,
    ScalarT* state109NP1,
    ScalarT* state110NP1,
    ScalarT* state111NP1,
    ScalarT* state112NP1,
    ScalarT* state113NP1,
    ScalarT* state114NP1,
    ScalarT* state115NP1,
    ScalarT* state116NP1,
    ScalarT* state117NP1,
    ScalarT* state118NP1,
    ScalarT* state119NP1,
    ScalarT* state120NP1,
    ScalarT* state121NP1,
    ScalarT* state122NP1,
    ScalarT* state123NP1,
    ScalarT* state124NP1,
    ScalarT* state125NP1,
    ScalarT* state126NP1,
    ScalarT* state127NP1,
    ScalarT* state128NP1,
    ScalarT* state129NP1,
    ScalarT* state130NP1,
    ScalarT* state131NP1,
    ScalarT* state132NP1,
    ScalarT* state133NP1,
    ScalarT* state134NP1,
    ScalarT* state135NP1,
    ScalarT* state136NP1,
    ScalarT* state137NP1,
    ScalarT* state138NP1,
    ScalarT* state139NP1,
    ScalarT* state140NP1,
    ScalarT* state141NP1,
    ScalarT* state142NP1,
    ScalarT* state143NP1,
    ScalarT* state144NP1,
    ScalarT* state145NP1,
    ScalarT* state146NP1,
    ScalarT* state147NP1,
    ScalarT* state148NP1,
    ScalarT* state149NP1,
    ScalarT* state150NP1,
    ScalarT* state151NP1,
    ScalarT* state152NP1,
    ScalarT* state153NP1,
    ScalarT* state154NP1,
    ScalarT* state155NP1,
    ScalarT* state156NP1,
    ScalarT* state157NP1,
    ScalarT* state158NP1,
    ScalarT* state159NP1,
    ScalarT* state160NP1,
    ScalarT* state161NP1,
    ScalarT* state162NP1,
    ScalarT* state163NP1,
    ScalarT* state164NP1,
    ScalarT* state165NP1,
    ScalarT* state166NP1,
    ScalarT* state167NP1,
    ScalarT* state168NP1,
    ScalarT* state169NP1,
    ScalarT* state170NP1,
    ScalarT* state171NP1,
    ScalarT* state172NP1,
    ScalarT* state173NP1,
    ScalarT* state174NP1,
    ScalarT* state175NP1,
    ScalarT* state176NP1,
    ScalarT* state177NP1,
    ScalarT* state178NP1,
    ScalarT* state179NP1,
    ScalarT* state180NP1,
    ScalarT* state181NP1,
    ScalarT* state182NP1,
    ScalarT* state183NP1,
    ScalarT* state184NP1,
    ScalarT* state185NP1,
    ScalarT* state186NP1,
    ScalarT* state187NP1,
    ScalarT* state188NP1,
    ScalarT* state189NP1,
    ScalarT* internalEnergyNP1,
    ScalarT* inelasticEnergyNP1,
    const int numPoints, 
    const double dt
);

template<typename ScalarT>
void updateBondLevelMicroplaneM7Stress
(
    const ScalarT* bondLevelStrainRateXX, 
    const ScalarT* bondLevelStrainRateXY, 
    const ScalarT* bondLevelStrainRateXZ, 
    const ScalarT* bondLevelStrainRateYX, 
    const ScalarT* bondLevelStrainRateYY, 
    const ScalarT* bondLevelStrainRateYZ, 
    const ScalarT* bondLevelStrainRateZX, 
    const ScalarT* bondLevelStrainRateZY, 
    const ScalarT* bondLevelStrainRateZZ, 
    const ScalarT* bondLevelStrainXX, 
    const ScalarT* bondLevelStrainXY, 
    const ScalarT* bondLevelStrainXZ, 
    const ScalarT* bondLevelStrainYX, 
    const ScalarT* bondLevelStrainYY, 
    const ScalarT* bondLevelStrainYZ, 
    const ScalarT* bondLevelStrainZX, 
    const ScalarT* bondLevelStrainZY, 
    const ScalarT* bondLevelStrainZZ, 
    const ScalarT* bondLevelStressXXN, 
    const ScalarT* bondLevelStressXYN, 
    const ScalarT* bondLevelStressXZN, 
    const ScalarT* bondLevelStressYXN, 
    const ScalarT* bondLevelStressYYN, 
    const ScalarT* bondLevelStressYZN, 
    const ScalarT* bondLevelStressZXN, 
    const ScalarT* bondLevelStressZYN, 
    const ScalarT* bondLevelStressZZN, 
    const ScalarT* bondLevelState1N,
    const ScalarT* bondLevelState2N,
    const ScalarT* bondLevelState3N,
    const ScalarT* bondLevelState4N,
    const ScalarT* bondLevelState5N,
    const ScalarT* bondLevelState6N,
    const ScalarT* bondLevelState7N,
    const ScalarT* bondLevelState8N,
    const ScalarT* bondLevelState9N,
    const ScalarT* bondLevelState10N,
    const ScalarT* bondLevelState11N,
    const ScalarT* bondLevelState12N,
    const ScalarT* bondLevelState13N,
    const ScalarT* bondLevelState14N,
    const ScalarT* bondLevelState15N,
    const ScalarT* bondLevelState16N,
    const ScalarT* bondLevelState17N,
    const ScalarT* bondLevelState18N,
    const ScalarT* bondLevelState19N,
    const ScalarT* bondLevelState20N,
    const ScalarT* bondLevelState21N,
    const ScalarT* bondLevelState22N,
    const ScalarT* bondLevelState23N,
    const ScalarT* bondLevelState24N,
    const ScalarT* bondLevelState25N,
    const ScalarT* bondLevelState26N,
    const ScalarT* bondLevelState27N,
    const ScalarT* bondLevelState28N,
    const ScalarT* bondLevelState29N,
    const ScalarT* bondLevelState30N,
    const ScalarT* bondLevelState31N,
    const ScalarT* bondLevelState32N,
    const ScalarT* bondLevelState33N,
    const ScalarT* bondLevelState34N,
    const ScalarT* bondLevelState35N,
    const ScalarT* bondLevelState36N,
    const ScalarT* bondLevelState37N,
    const ScalarT* bondLevelState38N,
    const ScalarT* bondLevelState39N,
    const ScalarT* bondLevelState40N,
    const ScalarT* bondLevelState41N,
    const ScalarT* bondLevelState42N,
    const ScalarT* bondLevelState43N,
    const ScalarT* bondLevelState44N,
    const ScalarT* bondLevelState45N,
    const ScalarT* bondLevelState46N,
    const ScalarT* bondLevelState47N,
    const ScalarT* bondLevelState48N,
    const ScalarT* bondLevelState49N,
    const ScalarT* bondLevelState50N,
    const ScalarT* bondLevelState51N,
    const ScalarT* bondLevelState52N,
    const ScalarT* bondLevelState53N,
    const ScalarT* bondLevelState54N,
    const ScalarT* bondLevelState55N,
    const ScalarT* bondLevelState56N,
    const ScalarT* bondLevelState57N,
    const ScalarT* bondLevelState58N,
    const ScalarT* bondLevelState59N,
    const ScalarT* bondLevelState60N,
    const ScalarT* bondLevelState61N,
    const ScalarT* bondLevelState62N,
    const ScalarT* bondLevelState63N,
    const ScalarT* bondLevelState64N,
    const ScalarT* bondLevelState65N,
    const ScalarT* bondLevelState66N,
    const ScalarT* bondLevelState67N,
    const ScalarT* bondLevelState68N,
    const ScalarT* bondLevelState69N,
    const ScalarT* bondLevelState70N,
    const ScalarT* bondLevelState71N,
    const ScalarT* bondLevelState72N,
    const ScalarT* bondLevelState73N,
    const ScalarT* bondLevelState74N,
    const ScalarT* bondLevelState75N,
    const ScalarT* bondLevelState76N,
    const ScalarT* bondLevelState77N,
    const ScalarT* bondLevelState78N,
    const ScalarT* bondLevelState79N,
    const ScalarT* bondLevelState80N,
    const ScalarT* bondLevelState81N,
    const ScalarT* bondLevelState82N,
    const ScalarT* bondLevelState83N,
    const ScalarT* bondLevelState84N,
    const ScalarT* bondLevelState85N,
    const ScalarT* bondLevelState86N,
    const ScalarT* bondLevelState87N,
    const ScalarT* bondLevelState88N,
    const ScalarT* bondLevelState89N,
    const ScalarT* bondLevelState90N,
    const ScalarT* bondLevelState91N,
    const ScalarT* bondLevelState92N,
    const ScalarT* bondLevelState93N,
    const ScalarT* bondLevelState94N,
    const ScalarT* bondLevelState95N,
    const ScalarT* bondLevelState96N,
    const ScalarT* bondLevelState97N,
    const ScalarT* bondLevelState98N,
    const ScalarT* bondLevelState99N,
    const ScalarT* bondLevelState100N,
    const ScalarT* bondLevelState101N,
    const ScalarT* bondLevelState102N,
    const ScalarT* bondLevelState103N,
    const ScalarT* bondLevelState104N,
    const ScalarT* bondLevelState105N,
    const ScalarT* bondLevelState106N,
    const ScalarT* bondLevelState107N,
    const ScalarT* bondLevelState108N,
    const ScalarT* bondLevelState109N,
    const ScalarT* bondLevelState110N,
    const ScalarT* bondLevelState111N,
    const ScalarT* bondLevelState112N,
    const ScalarT* bondLevelState113N,
    const ScalarT* bondLevelState114N,
    const ScalarT* bondLevelState115N,
    const ScalarT* bondLevelState116N,
    const ScalarT* bondLevelState117N,
    const ScalarT* bondLevelState118N,
    const ScalarT* bondLevelState119N,
    const ScalarT* bondLevelState120N,
    const ScalarT* bondLevelState121N,
    const ScalarT* bondLevelState122N,
    const ScalarT* bondLevelState123N,
    const ScalarT* bondLevelState124N,
    const ScalarT* bondLevelState125N,
    const ScalarT* bondLevelState126N,
    const ScalarT* bondLevelState127N,
    const ScalarT* bondLevelState128N,
    const ScalarT* bondLevelState129N,
    const ScalarT* bondLevelState130N,
    const ScalarT* bondLevelState131N,
    const ScalarT* bondLevelState132N,
    const ScalarT* bondLevelState133N,
    const ScalarT* bondLevelState134N,
    const ScalarT* bondLevelState135N,
    const ScalarT* bondLevelState136N,
    const ScalarT* bondLevelState137N,
    const ScalarT* bondLevelState138N,
    const ScalarT* bondLevelState139N,
    const ScalarT* bondLevelState140N,
    const ScalarT* bondLevelState141N,
    const ScalarT* bondLevelState142N,
    const ScalarT* bondLevelState143N,
    const ScalarT* bondLevelState144N,
    const ScalarT* bondLevelState145N,
    const ScalarT* bondLevelState146N,
    const ScalarT* bondLevelState147N,
    const ScalarT* bondLevelState148N,
    const ScalarT* bondLevelState149N,
    const ScalarT* bondLevelState150N,
    const ScalarT* bondLevelState151N,
    const ScalarT* bondLevelState152N,
    const ScalarT* bondLevelState153N,
    const ScalarT* bondLevelState154N,
    const ScalarT* bondLevelState155N,
    const ScalarT* bondLevelState156N,
    const ScalarT* bondLevelState157N,
    const ScalarT* bondLevelState158N,
    const ScalarT* bondLevelState159N,
    const ScalarT* bondLevelState160N,
    const ScalarT* bondLevelState161N,
    const ScalarT* bondLevelState162N,
    const ScalarT* bondLevelState163N,
    const ScalarT* bondLevelState164N,
    const ScalarT* bondLevelState165N,
    const ScalarT* bondLevelState166N,
    const ScalarT* bondLevelState167N,
    const ScalarT* bondLevelState168N,
    const ScalarT* bondLevelState169N,
    const ScalarT* bondLevelState170N,
    const ScalarT* bondLevelState171N,
    const ScalarT* bondLevelState172N,
    const ScalarT* bondLevelState173N,
    const ScalarT* bondLevelState174N,
    const ScalarT* bondLevelState175N,
    const ScalarT* bondLevelState176N,
    const ScalarT* bondLevelState177N,
    const ScalarT* bondLevelState178N,
    const ScalarT* bondLevelState179N,
    const ScalarT* bondLevelState180N,
    const ScalarT* bondLevelState181N,
    const ScalarT* bondLevelState182N,
    const ScalarT* bondLevelState183N,
    const ScalarT* bondLevelState184N,
    const ScalarT* bondLevelState185N,
    const ScalarT* bondLevelState186N,
    const ScalarT* bondLevelState187N,
    const ScalarT* bondLevelState188N,
    const ScalarT* bondLevelState189N,
    const ScalarT* bondLevelInternalEnergyN,
    const ScalarT* bondLevelInelasticEnergyN,
    ScalarT* bondLevelStressXXNP1, 
    ScalarT* bondLevelStressXYNP1, 
    ScalarT* bondLevelStressXZNP1, 
    ScalarT* bondLevelStressYXNP1, 
    ScalarT* bondLevelStressYYNP1, 
    ScalarT* bondLevelStressYZNP1, 
    ScalarT* bondLevelStressZXNP1, 
    ScalarT* bondLevelStressZYNP1, 
    ScalarT* bondLevelStressZZNP1, 
    ScalarT* bondLevelState1NP1,
    ScalarT* bondLevelState2NP1,
    ScalarT* bondLevelState3NP1,
    ScalarT* bondLevelState4NP1,
    ScalarT* bondLevelState5NP1,
    ScalarT* bondLevelState6NP1,
    ScalarT* bondLevelState7NP1,
    ScalarT* bondLevelState8NP1,
    ScalarT* bondLevelState9NP1,
    ScalarT* bondLevelState10NP1,
    ScalarT* bondLevelState11NP1,
    ScalarT* bondLevelState12NP1,
    ScalarT* bondLevelState13NP1,
    ScalarT* bondLevelState14NP1,
    ScalarT* bondLevelState15NP1,
    ScalarT* bondLevelState16NP1,
    ScalarT* bondLevelState17NP1,
    ScalarT* bondLevelState18NP1,
    ScalarT* bondLevelState19NP1,
    ScalarT* bondLevelState20NP1,
    ScalarT* bondLevelState21NP1,
    ScalarT* bondLevelState22NP1,
    ScalarT* bondLevelState23NP1,
    ScalarT* bondLevelState24NP1,
    ScalarT* bondLevelState25NP1,
    ScalarT* bondLevelState26NP1,
    ScalarT* bondLevelState27NP1,
    ScalarT* bondLevelState28NP1,
    ScalarT* bondLevelState29NP1,
    ScalarT* bondLevelState30NP1,
    ScalarT* bondLevelState31NP1,
    ScalarT* bondLevelState32NP1,
    ScalarT* bondLevelState33NP1,
    ScalarT* bondLevelState34NP1,
    ScalarT* bondLevelState35NP1,
    ScalarT* bondLevelState36NP1,
    ScalarT* bondLevelState37NP1,
    ScalarT* bondLevelState38NP1,
    ScalarT* bondLevelState39NP1,
    ScalarT* bondLevelState40NP1,
    ScalarT* bondLevelState41NP1,
    ScalarT* bondLevelState42NP1,
    ScalarT* bondLevelState43NP1,
    ScalarT* bondLevelState44NP1,
    ScalarT* bondLevelState45NP1,
    ScalarT* bondLevelState46NP1,
    ScalarT* bondLevelState47NP1,
    ScalarT* bondLevelState48NP1,
    ScalarT* bondLevelState49NP1,
    ScalarT* bondLevelState50NP1,
    ScalarT* bondLevelState51NP1,
    ScalarT* bondLevelState52NP1,
    ScalarT* bondLevelState53NP1,
    ScalarT* bondLevelState54NP1,
    ScalarT* bondLevelState55NP1,
    ScalarT* bondLevelState56NP1,
    ScalarT* bondLevelState57NP1,
    ScalarT* bondLevelState58NP1,
    ScalarT* bondLevelState59NP1,
    ScalarT* bondLevelState60NP1,
    ScalarT* bondLevelState61NP1,
    ScalarT* bondLevelState62NP1,
    ScalarT* bondLevelState63NP1,
    ScalarT* bondLevelState64NP1,
    ScalarT* bondLevelState65NP1,
    ScalarT* bondLevelState66NP1,
    ScalarT* bondLevelState67NP1,
    ScalarT* bondLevelState68NP1,
    ScalarT* bondLevelState69NP1,
    ScalarT* bondLevelState70NP1,
    ScalarT* bondLevelState71NP1,
    ScalarT* bondLevelState72NP1,
    ScalarT* bondLevelState73NP1,
    ScalarT* bondLevelState74NP1,
    ScalarT* bondLevelState75NP1,
    ScalarT* bondLevelState76NP1,
    ScalarT* bondLevelState77NP1,
    ScalarT* bondLevelState78NP1,
    ScalarT* bondLevelState79NP1,
    ScalarT* bondLevelState80NP1,
    ScalarT* bondLevelState81NP1,
    ScalarT* bondLevelState82NP1,
    ScalarT* bondLevelState83NP1,
    ScalarT* bondLevelState84NP1,
    ScalarT* bondLevelState85NP1,
    ScalarT* bondLevelState86NP1,
    ScalarT* bondLevelState87NP1,
    ScalarT* bondLevelState88NP1,
    ScalarT* bondLevelState89NP1,
    ScalarT* bondLevelState90NP1,
    ScalarT* bondLevelState91NP1,
    ScalarT* bondLevelState92NP1,
    ScalarT* bondLevelState93NP1,
    ScalarT* bondLevelState94NP1,
    ScalarT* bondLevelState95NP1,
    ScalarT* bondLevelState96NP1,
    ScalarT* bondLevelState97NP1,
    ScalarT* bondLevelState98NP1,
    ScalarT* bondLevelState99NP1,
    ScalarT* bondLevelState100NP1,
    ScalarT* bondLevelState101NP1,
    ScalarT* bondLevelState102NP1,
    ScalarT* bondLevelState103NP1,
    ScalarT* bondLevelState104NP1,
    ScalarT* bondLevelState105NP1,
    ScalarT* bondLevelState106NP1,
    ScalarT* bondLevelState107NP1,
    ScalarT* bondLevelState108NP1,
    ScalarT* bondLevelState109NP1,
    ScalarT* bondLevelState110NP1,
    ScalarT* bondLevelState111NP1,
    ScalarT* bondLevelState112NP1,
    ScalarT* bondLevelState113NP1,
    ScalarT* bondLevelState114NP1,
    ScalarT* bondLevelState115NP1,
    ScalarT* bondLevelState116NP1,
    ScalarT* bondLevelState117NP1,
    ScalarT* bondLevelState118NP1,
    ScalarT* bondLevelState119NP1,
    ScalarT* bondLevelState120NP1,
    ScalarT* bondLevelState121NP1,
    ScalarT* bondLevelState122NP1,
    ScalarT* bondLevelState123NP1,
    ScalarT* bondLevelState124NP1,
    ScalarT* bondLevelState125NP1,
    ScalarT* bondLevelState126NP1,
    ScalarT* bondLevelState127NP1,
    ScalarT* bondLevelState128NP1,
    ScalarT* bondLevelState129NP1,
    ScalarT* bondLevelState130NP1,
    ScalarT* bondLevelState131NP1,
    ScalarT* bondLevelState132NP1,
    ScalarT* bondLevelState133NP1,
    ScalarT* bondLevelState134NP1,
    ScalarT* bondLevelState135NP1,
    ScalarT* bondLevelState136NP1,
    ScalarT* bondLevelState137NP1,
    ScalarT* bondLevelState138NP1,
    ScalarT* bondLevelState139NP1,
    ScalarT* bondLevelState140NP1,
    ScalarT* bondLevelState141NP1,
    ScalarT* bondLevelState142NP1,
    ScalarT* bondLevelState143NP1,
    ScalarT* bondLevelState144NP1,
    ScalarT* bondLevelState145NP1,
    ScalarT* bondLevelState146NP1,
    ScalarT* bondLevelState147NP1,
    ScalarT* bondLevelState148NP1,
    ScalarT* bondLevelState149NP1,
    ScalarT* bondLevelState150NP1,
    ScalarT* bondLevelState151NP1,
    ScalarT* bondLevelState152NP1,
    ScalarT* bondLevelState153NP1,
    ScalarT* bondLevelState154NP1,
    ScalarT* bondLevelState155NP1,
    ScalarT* bondLevelState156NP1,
    ScalarT* bondLevelState157NP1,
    ScalarT* bondLevelState158NP1,
    ScalarT* bondLevelState159NP1,
    ScalarT* bondLevelState160NP1,
    ScalarT* bondLevelState161NP1,
    ScalarT* bondLevelState162NP1,
    ScalarT* bondLevelState163NP1,
    ScalarT* bondLevelState164NP1,
    ScalarT* bondLevelState165NP1,
    ScalarT* bondLevelState166NP1,
    ScalarT* bondLevelState167NP1,
    ScalarT* bondLevelState168NP1,
    ScalarT* bondLevelState169NP1,
    ScalarT* bondLevelState170NP1,
    ScalarT* bondLevelState171NP1,
    ScalarT* bondLevelState172NP1,
    ScalarT* bondLevelState173NP1,
    ScalarT* bondLevelState174NP1,
    ScalarT* bondLevelState175NP1,
    ScalarT* bondLevelState176NP1,
    ScalarT* bondLevelState177NP1,
    ScalarT* bondLevelState178NP1,
    ScalarT* bondLevelState179NP1,
    ScalarT* bondLevelState180NP1,
    ScalarT* bondLevelState181NP1,
    ScalarT* bondLevelState182NP1,
    ScalarT* bondLevelState183NP1,
    ScalarT* bondLevelState184NP1,
    ScalarT* bondLevelState185NP1,
    ScalarT* bondLevelState186NP1,
    ScalarT* bondLevelState187NP1,
    ScalarT* bondLevelState188NP1,
    ScalarT* bondLevelState189NP1,
    ScalarT* bondLevelInternalEnergyNP1,
    ScalarT* bondLevelInelasticEnergyNP1,
    const int* neighborhoodList,
    const int numPoints, 
    const double dt
);

}

#endif // MICROPLANE_CORRESPONDENCE_H
